//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AKSOptions) DeepCopyInto(out *AKSOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AKSOptions.
func (in *AKSOptions) DeepCopy() *AKSOptions {
	if in == nil {
		return nil
	}
	out := new(AKSOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroClusterManager) DeepCopyInto(out *AeroClusterManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroClusterManager.
func (in *AeroClusterManager) DeepCopy() *AeroClusterManager {
	if in == nil {
		return nil
	}
	out := new(AeroClusterManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AeroClusterManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroClusterManagerList) DeepCopyInto(out *AeroClusterManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AeroClusterManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroClusterManagerList.
func (in *AeroClusterManagerList) DeepCopy() *AeroClusterManagerList {
	if in == nil {
		return nil
	}
	out := new(AeroClusterManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AeroClusterManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroClusterManagerSpec) DeepCopyInto(out *AeroClusterManagerSpec) {
	*out = *in
	in.ClusterOptions.DeepCopyInto(&out.ClusterOptions)
	out.ClusterID = in.ClusterID
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroClusterManagerSpec.
func (in *AeroClusterManagerSpec) DeepCopy() *AeroClusterManagerSpec {
	if in == nil {
		return nil
	}
	out := new(AeroClusterManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroClusterManagerStatus) DeepCopyInto(out *AeroClusterManagerStatus) {
	*out = *in
	out.AerospikeOperator = in.AerospikeOperator
	out.PrometheusExporter = in.PrometheusExporter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroClusterManagerStatus.
func (in *AeroClusterManagerStatus) DeepCopy() *AeroClusterManagerStatus {
	if in == nil {
		return nil
	}
	out := new(AeroClusterManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroDatabase) DeepCopyInto(out *AeroDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroDatabase.
func (in *AeroDatabase) DeepCopy() *AeroDatabase {
	if in == nil {
		return nil
	}
	out := new(AeroDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AeroDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroDatabaseList) DeepCopyInto(out *AeroDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AeroDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroDatabaseList.
func (in *AeroDatabaseList) DeepCopy() *AeroDatabaseList {
	if in == nil {
		return nil
	}
	out := new(AeroDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AeroDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroDatabaseSpec) DeepCopyInto(out *AeroDatabaseSpec) {
	*out = *in
	out.Cluster = in.Cluster
	out.Options = in.Options
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroDatabaseSpec.
func (in *AeroDatabaseSpec) DeepCopy() *AeroDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(AeroDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AeroDatabaseStatus) DeepCopyInto(out *AeroDatabaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AeroDatabaseStatus.
func (in *AeroDatabaseStatus) DeepCopy() *AeroDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(AeroDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKey) DeepCopyInto(out *ClusterKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKey.
func (in *ClusterKey) DeepCopy() *ClusterKey {
	if in == nil {
		return nil
	}
	out := new(ClusterKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOptions) DeepCopyInto(out *ClusterOptions) {
	*out = *in
	if in.DockerOptions != nil {
		in, out := &in.DockerOptions, &out.DockerOptions
		*out = new(DockerOptions)
		**out = **in
	}
	if in.EKSOptions != nil {
		in, out := &in.EKSOptions, &out.EKSOptions
		*out = new(EKSOptions)
		**out = **in
	}
	if in.AKSOptions != nil {
		in, out := &in.AKSOptions, &out.AKSOptions
		*out = new(AKSOptions)
		**out = **in
	}
	if in.GKEOptions != nil {
		in, out := &in.GKEOptions, &out.GKEOptions
		*out = new(GKEOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOptions.
func (in *ClusterOptions) DeepCopy() *ClusterOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseOptions) DeepCopyInto(out *DatabaseOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseOptions.
func (in *DatabaseOptions) DeepCopy() *DatabaseOptions {
	if in == nil {
		return nil
	}
	out := new(DatabaseOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerOptions) DeepCopyInto(out *DockerOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerOptions.
func (in *DockerOptions) DeepCopy() *DockerOptions {
	if in == nil {
		return nil
	}
	out := new(DockerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSOptions) DeepCopyInto(out *EKSOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSOptions.
func (in *EKSOptions) DeepCopy() *EKSOptions {
	if in == nil {
		return nil
	}
	out := new(EKSOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEOptions) DeepCopyInto(out *GKEOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEOptions.
func (in *GKEOptions) DeepCopy() *GKEOptions {
	if in == nil {
		return nil
	}
	out := new(GKEOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}
