// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: kubernetes.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetKubernetesClusterRequest) Reset() {
	*x = GetKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubernetesClusterRequest) ProtoMessage() {}

func (x *GetKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*GetKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{0}
}

func (x *GetKubernetesClusterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetKubernetesClustersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
}

func (x *GetKubernetesClustersRequest) Reset() {
	*x = GetKubernetesClustersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKubernetesClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubernetesClustersRequest) ProtoMessage() {}

func (x *GetKubernetesClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubernetesClustersRequest.ProtoReflect.Descriptor instead.
func (*GetKubernetesClustersRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{1}
}

func (x *GetKubernetesClustersRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetKubernetesClustersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clusters []byte `protobuf:"bytes,1,opt,name=Clusters,proto3" json:"Clusters,omitempty"`
}

func (x *GetKubernetesClustersResponse) Reset() {
	*x = GetKubernetesClustersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKubernetesClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubernetesClustersResponse) ProtoMessage() {}

func (x *GetKubernetesClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubernetesClustersResponse.ProtoReflect.Descriptor instead.
func (*GetKubernetesClustersResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{2}
}

func (x *GetKubernetesClustersResponse) GetClusters() []byte {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type NamespacedName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
}

func (x *NamespacedName) Reset() {
	*x = NamespacedName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespacedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedName) ProtoMessage() {}

func (x *NamespacedName) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedName.ProtoReflect.Descriptor instead.
func (*NamespacedName) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{3}
}

func (x *NamespacedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespacedName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetKubernetesClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster []byte `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Status  []byte `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GetKubernetesClusterResponse) Reset() {
	*x = GetKubernetesClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKubernetesClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubernetesClusterResponse) ProtoMessage() {}

func (x *GetKubernetesClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubernetesClusterResponse.ProtoReflect.Descriptor instead.
func (*GetKubernetesClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{4}
}

func (x *GetKubernetesClusterResponse) GetCluster() []byte {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *GetKubernetesClusterResponse) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type CreateKubernetesClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKubernetesClusterResponse) Reset() {
	*x = CreateKubernetesClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKubernetesClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKubernetesClusterResponse) ProtoMessage() {}

func (x *CreateKubernetesClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKubernetesClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateKubernetesClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{5}
}

type UpdateKubernetesClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateKubernetesClusterResponse) Reset() {
	*x = UpdateKubernetesClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKubernetesClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKubernetesClusterResponse) ProtoMessage() {}

func (x *UpdateKubernetesClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKubernetesClusterResponse.ProtoReflect.Descriptor instead.
func (*UpdateKubernetesClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{6}
}

type DeleteKubernetesClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKubernetesClusterResponse) Reset() {
	*x = DeleteKubernetesClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubernetesClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubernetesClusterResponse) ProtoMessage() {}

func (x *DeleteKubernetesClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubernetesClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteKubernetesClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{7}
}

type CreateKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                                `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace   string                                `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Eks         *CreateEKSKubernetesClusterRequest    `protobuf:"bytes,3,opt,name=Eks,proto3" json:"Eks,omitempty"`
	Aks         *CreateAKSKubernetesClusterRequest    `protobuf:"bytes,4,opt,name=Aks,proto3" json:"Aks,omitempty"`
	Gke         *CreateGCPKubernetesClusterRequest    `protobuf:"bytes,5,opt,name=Gke,proto3" json:"Gke,omitempty"`
	Docker      *CreateDockerKubernetesClusterRequest `protobuf:"bytes,6,opt,name=Docker,proto3" json:"Docker,omitempty"`
	Provider    string                                `protobuf:"bytes,7,opt,name=Provider,proto3" json:"Provider,omitempty"`
	KubeVersion string                                `protobuf:"bytes,8,opt,name=KubeVersion,proto3" json:"KubeVersion,omitempty"`
	Replicas    int32                                 `protobuf:"varint,9,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
}

func (x *CreateKubernetesClusterRequest) Reset() {
	*x = CreateKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKubernetesClusterRequest) ProtoMessage() {}

func (x *CreateKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{8}
}

func (x *CreateKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKubernetesClusterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateKubernetesClusterRequest) GetEks() *CreateEKSKubernetesClusterRequest {
	if x != nil {
		return x.Eks
	}
	return nil
}

func (x *CreateKubernetesClusterRequest) GetAks() *CreateAKSKubernetesClusterRequest {
	if x != nil {
		return x.Aks
	}
	return nil
}

func (x *CreateKubernetesClusterRequest) GetGke() *CreateGCPKubernetesClusterRequest {
	if x != nil {
		return x.Gke
	}
	return nil
}

func (x *CreateKubernetesClusterRequest) GetDocker() *CreateDockerKubernetesClusterRequest {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *CreateKubernetesClusterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateKubernetesClusterRequest) GetKubeVersion() string {
	if x != nil {
		return x.KubeVersion
	}
	return ""
}

func (x *CreateKubernetesClusterRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type CreateDockerKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDockerKubernetesClusterRequest) Reset() {
	*x = CreateDockerKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDockerKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDockerKubernetesClusterRequest) ProtoMessage() {}

func (x *CreateDockerKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDockerKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateDockerKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{9}
}

type CreateEKSKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region       string `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	InstanceType string `protobuf:"bytes,2,opt,name=InstanceType,proto3" json:"InstanceType,omitempty"`
	SSHKey       string `protobuf:"bytes,3,opt,name=SSHKey,proto3" json:"SSHKey,omitempty"`
}

func (x *CreateEKSKubernetesClusterRequest) Reset() {
	*x = CreateEKSKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEKSKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEKSKubernetesClusterRequest) ProtoMessage() {}

func (x *CreateEKSKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEKSKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateEKSKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{10}
}

func (x *CreateEKSKubernetesClusterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateEKSKubernetesClusterRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *CreateEKSKubernetesClusterRequest) GetSSHKey() string {
	if x != nil {
		return x.SSHKey
	}
	return ""
}

type CreateAKSKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Region       string `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	InstanceType string `protobuf:"bytes,3,opt,name=InstanceType,proto3" json:"InstanceType,omitempty"`
	SSHKey       string `protobuf:"bytes,4,opt,name=SSHKey,proto3" json:"SSHKey,omitempty"`
}

func (x *CreateAKSKubernetesClusterRequest) Reset() {
	*x = CreateAKSKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAKSKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAKSKubernetesClusterRequest) ProtoMessage() {}

func (x *CreateAKSKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAKSKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateAKSKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAKSKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAKSKubernetesClusterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateAKSKubernetesClusterRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *CreateAKSKubernetesClusterRequest) GetSSHKey() string {
	if x != nil {
		return x.SSHKey
	}
	return ""
}

type CreateGCPKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Region       string `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	InstanceType string `protobuf:"bytes,3,opt,name=InstanceType,proto3" json:"InstanceType,omitempty"`
	SSHKey       string `protobuf:"bytes,4,opt,name=SSHKey,proto3" json:"SSHKey,omitempty"`
}

func (x *CreateGCPKubernetesClusterRequest) Reset() {
	*x = CreateGCPKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGCPKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGCPKubernetesClusterRequest) ProtoMessage() {}

func (x *CreateGCPKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGCPKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateGCPKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGCPKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGCPKubernetesClusterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateGCPKubernetesClusterRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *CreateGCPKubernetesClusterRequest) GetSSHKey() string {
	if x != nil {
		return x.SSHKey
	}
	return ""
}

type DeleteKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
}

func (x *DeleteKubernetesClusterRequest) Reset() {
	*x = DeleteKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubernetesClusterRequest) ProtoMessage() {}

func (x *DeleteKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteKubernetesClusterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type UpdateKubernetesClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                                `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace string                                `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Eks       *CreateEKSKubernetesClusterRequest    `protobuf:"bytes,3,opt,name=Eks,proto3" json:"Eks,omitempty"`
	Aks       *CreateAKSKubernetesClusterRequest    `protobuf:"bytes,4,opt,name=Aks,proto3" json:"Aks,omitempty"`
	Gke       *CreateGCPKubernetesClusterRequest    `protobuf:"bytes,5,opt,name=Gke,proto3" json:"Gke,omitempty"`
	Docker    *CreateDockerKubernetesClusterRequest `protobuf:"bytes,6,opt,name=Docker,proto3" json:"Docker,omitempty"`
	Replicas  int32                                 `protobuf:"varint,7,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
}

func (x *UpdateKubernetesClusterRequest) Reset() {
	*x = UpdateKubernetesClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kubernetes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKubernetesClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKubernetesClusterRequest) ProtoMessage() {}

func (x *UpdateKubernetesClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKubernetesClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateKubernetesClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateKubernetesClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKubernetesClusterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateKubernetesClusterRequest) GetEks() *CreateEKSKubernetesClusterRequest {
	if x != nil {
		return x.Eks
	}
	return nil
}

func (x *UpdateKubernetesClusterRequest) GetAks() *CreateAKSKubernetesClusterRequest {
	if x != nil {
		return x.Aks
	}
	return nil
}

func (x *UpdateKubernetesClusterRequest) GetGke() *CreateGCPKubernetesClusterRequest {
	if x != nil {
		return x.Gke
	}
	return nil
}

func (x *UpdateKubernetesClusterRequest) GetDocker() *CreateDockerKubernetesClusterRequest {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *UpdateKubernetesClusterRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

var File_kubernetes_proto protoreflect.FileDescriptor

var file_kubernetes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4f, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x22, 0x42, 0x0a, 0x0e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x50, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21,
	0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x21, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb1, 0x03, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x03,
	0x45, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x53, 0x4b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x45, 0x6b, 0x73, 0x12, 0x3d, 0x0a, 0x03, 0x41,
	0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x4b, 0x53, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x41, 0x6b, 0x73, 0x12, 0x3d, 0x0a, 0x03, 0x47, 0x6b,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x43, 0x50, 0x4b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x47, 0x6b, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x44, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x4b, 0x75, 0x62, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4b, 0x75, 0x62, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x26, 0x0a, 0x24, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4b, 0x53,
	0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a,
	0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x4b, 0x53, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x21, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x43, 0x50, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x22, 0x52, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xf3, 0x02, 0x0a,
	0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x03, 0x45, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x4b, 0x53, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x45, 0x6b, 0x73,
	0x12, 0x3d, 0x0a, 0x03, 0x41, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x4b, 0x53, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x41, 0x6b, 0x73, 0x12,
	0x3d, 0x0a, 0x03, 0x47, 0x6b, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x43,
	0x50, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x47, 0x6b, 0x65, 0x12, 0x46,
	0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x65, 0x72, 0x6f, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x61, 0x65, 0x72, 0x6f, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x61, 0x70, 0x69, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kubernetes_proto_rawDescOnce sync.Once
	file_kubernetes_proto_rawDescData = file_kubernetes_proto_rawDesc
)

func file_kubernetes_proto_rawDescGZIP() []byte {
	file_kubernetes_proto_rawDescOnce.Do(func() {
		file_kubernetes_proto_rawDescData = protoimpl.X.CompressGZIP(file_kubernetes_proto_rawDescData)
	})
	return file_kubernetes_proto_rawDescData
}

var file_kubernetes_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kubernetes_proto_goTypes = []interface{}{
	(*GetKubernetesClusterRequest)(nil),          // 0: messages.GetKubernetesClusterRequest
	(*GetKubernetesClustersRequest)(nil),         // 1: messages.GetKubernetesClustersRequest
	(*GetKubernetesClustersResponse)(nil),        // 2: messages.GetKubernetesClustersResponse
	(*NamespacedName)(nil),                       // 3: messages.NamespacedName
	(*GetKubernetesClusterResponse)(nil),         // 4: messages.GetKubernetesClusterResponse
	(*CreateKubernetesClusterResponse)(nil),      // 5: messages.CreateKubernetesClusterResponse
	(*UpdateKubernetesClusterResponse)(nil),      // 6: messages.UpdateKubernetesClusterResponse
	(*DeleteKubernetesClusterResponse)(nil),      // 7: messages.DeleteKubernetesClusterResponse
	(*CreateKubernetesClusterRequest)(nil),       // 8: messages.CreateKubernetesClusterRequest
	(*CreateDockerKubernetesClusterRequest)(nil), // 9: messages.CreateDockerKubernetesClusterRequest
	(*CreateEKSKubernetesClusterRequest)(nil),    // 10: messages.CreateEKSKubernetesClusterRequest
	(*CreateAKSKubernetesClusterRequest)(nil),    // 11: messages.CreateAKSKubernetesClusterRequest
	(*CreateGCPKubernetesClusterRequest)(nil),    // 12: messages.CreateGCPKubernetesClusterRequest
	(*DeleteKubernetesClusterRequest)(nil),       // 13: messages.DeleteKubernetesClusterRequest
	(*UpdateKubernetesClusterRequest)(nil),       // 14: messages.UpdateKubernetesClusterRequest
}
var file_kubernetes_proto_depIdxs = []int32{
	10, // 0: messages.CreateKubernetesClusterRequest.Eks:type_name -> messages.CreateEKSKubernetesClusterRequest
	11, // 1: messages.CreateKubernetesClusterRequest.Aks:type_name -> messages.CreateAKSKubernetesClusterRequest
	12, // 2: messages.CreateKubernetesClusterRequest.Gke:type_name -> messages.CreateGCPKubernetesClusterRequest
	9,  // 3: messages.CreateKubernetesClusterRequest.Docker:type_name -> messages.CreateDockerKubernetesClusterRequest
	10, // 4: messages.UpdateKubernetesClusterRequest.Eks:type_name -> messages.CreateEKSKubernetesClusterRequest
	11, // 5: messages.UpdateKubernetesClusterRequest.Aks:type_name -> messages.CreateAKSKubernetesClusterRequest
	12, // 6: messages.UpdateKubernetesClusterRequest.Gke:type_name -> messages.CreateGCPKubernetesClusterRequest
	9,  // 7: messages.UpdateKubernetesClusterRequest.Docker:type_name -> messages.CreateDockerKubernetesClusterRequest
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kubernetes_proto_init() }
func file_kubernetes_proto_init() {
	if File_kubernetes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kubernetes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKubernetesClustersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKubernetesClustersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespacedName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKubernetesClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKubernetesClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKubernetesClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubernetesClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDockerKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEKSKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAKSKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGCPKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kubernetes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKubernetesClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kubernetes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubernetes_proto_goTypes,
		DependencyIndexes: file_kubernetes_proto_depIdxs,
		MessageInfos:      file_kubernetes_proto_msgTypes,
	}.Build()
	File_kubernetes_proto = out.File
	file_kubernetes_proto_rawDesc = nil
	file_kubernetes_proto_goTypes = nil
	file_kubernetes_proto_depIdxs = nil
}
