name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: RyanSiu1995/kubebuilder-action@v1.2
      with:
        version: 3.0.0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
