name: pr-unit-tests
'on':
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
    - name: run tests
      run: make test
